[project]
name = "capl-tree-sitter"
version = "0.1.0"
description = "Tree-sitter parsing & AST utilities for CAPL"
readme = "README.md"
authors = [
    { name = "MohamedHamed19m", email = "mohamedahamed1915@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "tree-sitter>=0.21.0",
    "tree-sitter-c>=0.21.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/capl_tree_sitter"]