[project]
name = "capl-linter"
version = "0.1.0"
description = "Analysis engine & auto-fix logic for CAPL"
readme = "README.md"
authors = [
    { name = "MohamedHamed19m", email = "mohamedahamed1915@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "capl-tree-sitter>=0.1.0",
    "capl-symbol-db>=0.1.0",
]

[tool.uv.sources]
capl-tree-sitter = { workspace = true }
capl-symbol-db = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/capl_linter"]